source 'https://rubygems.org'

gem 'debase'
gem 'fastri'
gem 'rcodetools'
gem 'rubocop'
gem 'ruby-debug-ide'

gem 'activerecord', '< 5.0.0'
gem 'dotenv'
gem 'pg', '0.18'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
